/*
 * MainForm.java
 *
 * Created on May 29, 2008, 3:59 PM
 */
package sts.gui;

import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultListModel;
import sts.Main;
import sts.game.Game;
import sts.game.InertAI;
import sts.game.Player;

/**
 *
 * @author  PC78064
 */
public class MainForm extends javax.swing.JFrame
{
    DefaultListModel data = new DefaultListModel();

    /** Creates new form MainForm */
    public MainForm()
    {
        initComponents();

        data.addElement( "You" );
        playerList.setModel( data );
        setVisible( true );

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        startGame = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        playerPanel = new javax.swing.JPanel();
        playerListScroller = new javax.swing.JScrollPane();
        playerList = new javax.swing.JList();
        remove = new javax.swing.JButton();
        add = new javax.swing.JButton();
        human = new javax.swing.JRadioButton();
        CPU = new javax.swing.JRadioButton();
        playerName = new javax.swing.JTextField();
        turbo = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title.setText("Schramts!");

        startGame.setText("Start game");
        startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        playerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Players"));

        playerListScroller.setViewportView(playerList);

        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        buttonGroup1.add(human);
        human.setText("Human");
        human.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                humanActionPerformed(evt);
            }
        });

        buttonGroup1.add(CPU);
        CPU.setSelected(true);
        CPU.setText("CPU");
        CPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPUActionPerformed(evt);
            }
        });

        playerName.setText("Name");
        playerName.setEnabled(false);

        org.jdesktop.layout.GroupLayout playerPanelLayout = new org.jdesktop.layout.GroupLayout(playerPanel);
        playerPanel.setLayout(playerPanelLayout);
        playerPanelLayout.setHorizontalGroup(
            playerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(playerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(playerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(playerListScroller, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                    .add(playerPanelLayout.createSequentialGroup()
                        .add(CPU)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(human)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(playerName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(add)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 75, Short.MAX_VALUE)
                        .add(remove)))
                .addContainerGap())
        );
        playerPanelLayout.setVerticalGroup(
            playerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(playerPanelLayout.createSequentialGroup()
                .add(playerListScroller, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(playerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(remove)
                    .add(human)
                    .add(playerName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(CPU)
                    .add(add)))
        );

        turbo.setText("Turbo");

        jButton1.setText("Help / About");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(exit)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 153, Short.MAX_VALUE)
                .add(turbo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(startGame)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .add(playerPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18))
            .add(layout.createSequentialGroup()
                .add(132, 132, 132)
                .add(title)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(title)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(playerPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 31, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(exit)
                        .add(jButton1))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(startGame)
                        .add(turbo)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    Main.quit();
}//GEN-LAST:event_exitActionPerformed

private void startGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameActionPerformed

    Set<Player> players = new HashSet<Player>();
    Player localPlayer = null;

    for ( int i = 0; i < data.getSize(); i++ )
    {
        String s = (String) data.getElementAt( i );

        if ( s.equals( "CPU" ) )
            players.add( new Player( Game.getPlayerColor( i ), s ) );
        else
        {
            localPlayer = new Player( Game.getPlayerColor( i ), s, new InertAI() );
            players.add( localPlayer );
        }
    }

    Main.startGame( players, localPlayer, turbo.isSelected() );
}//GEN-LAST:event_startGameActionPerformed

private void CPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPUActionPerformed
    playerName.setEnabled( false );
}//GEN-LAST:event_CPUActionPerformed

private void humanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_humanActionPerformed
    playerName.setEnabled( true );
}//GEN-LAST:event_humanActionPerformed

private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
    while ( !playerList.isSelectionEmpty() )
        data.remove( playerList.getSelectedIndex() );
}//GEN-LAST:event_removeActionPerformed

private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

    data.addElement( ( CPU.isSelected() ? "CPU" : playerName.getText() ) );
}//GEN-LAST:event_addActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new HelpAboutForm();
}//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CPU;
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton human;
    private javax.swing.JButton jButton1;
    private javax.swing.JList playerList;
    private javax.swing.JScrollPane playerListScroller;
    private javax.swing.JTextField playerName;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JButton remove;
    private javax.swing.JButton startGame;
    private javax.swing.JLabel title;
    private javax.swing.JCheckBox turbo;
    // End of variables declaration//GEN-END:variables

}
